###
### 검색어 랭킹 검색
GET http://localhost:8080/rank/v1
Accept: application/json

###
### 블로그 검색
GET http://localhost:8080/search/v1?query=TDD
Accept: application/json

###
### 블로그 검색
GET http://localhost:8080/search/v1?query=EDD
Accept: application/json

###
### 블로그 검색
GET http://localhost:8080/search/v1?query=ELK
Accept: application/json
