# Spring Properties
spring:
  profiles:
    active: local # set default profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # for swagger


# External Client Api
client:
  kakao:
    host: https://dapi.kakao.com
    api-key: "KakaoAK 8a1fc355ec8f1ea41603629966eda96f"
  naver:
    host: https://openapi.naver.com
    client-id: PLlTHKUsjpeQJ_zAh0WX
    client-secret: MQh6tlJAZR

